In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import sys
from pathlib import Path

project_root = Path.cwd().parents[1]
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.preprocessing import convert_dtypes

In [4]:
product_features = pd.read_csv(r"C:\Users\Lenovo\Customer-Intelligence-Platform\data\processed\product_summary_clean.csv")

In [8]:
product_features.head(5)

,product_id,product_category_name,total_units_sold,total_orders,total_revenue,total_freight,avg_price,avg_review_score,avg_delivery_days
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,1,1,101.65,18.59,101.65,5.0,17.0
1,00088930e925c41fd95ebfe695fd2655,automotivo,1,1,129.90,13.93,129.90,4.0,11.0
2,0009406fd7479715e4bef61dd91f2462,cama_mesa_banho,1,1,229.00,13.10,229.00,1.0,16.0
3,000b8f95fcb9e0096488278317764d19,utilidades_domesticas,2,2,117.80,39.20,58.90,5.0,6.5
4,000d9be29b5207b54e86aa1b1ac54872,relogios_presentes,1,1,199.00,19.27,199.00,5.0,7.0

### 1. Revenue per order
Revenue per Order= Total Orders / Total Revenue

	​

In [9]:
# Revenue generated per order
product_features["revenue_per_order"] = (
    product_features["total_revenue"]
    / product_features["total_orders"]
)

In [10]:
product_features["revenue_per_order"].isna().sum()

np.int64(0)

In [11]:

np.isinf(product_features["revenue_per_order"]).sum()

np.int64(0)

In [12]:
product_features["revenue_per_order"].describe()

count    32951.000000
mean       154.900335
std        269.063064
min          0.850000
25%         42.900000
50%         84.900000
75%        163.816667
max      13440.000000
Name: revenue_per_order, dtype: float64

In [13]:
product_features[
    [
        "total_revenue",
        "total_orders",
        "revenue_per_order"
    ]
].head(10)

   total_revenue  total_orders  revenue_per_order
0         101.65             1         101.650000
1         129.90             1         129.900000
2         229.00             1         229.000000
3         117.80             2          58.900000
4         199.00             1         199.000000
5          52.00             1          52.000000
6         498.00             2         249.000000
7         350.10             7          50.014286
8          78.90             1          78.900000
9         489.86            12          40.821667

### 2. Revenue per Unit

Revenue per Unit = Total Units Sold / Total Revenue​

In [14]:
product_features["revenue_per_unit"] = (
    product_features["total_revenue"]
    / product_features["total_units_sold"]
)

In [15]:
product_features["revenue_per_unit"].isna().sum()

np.int64(0)

In [16]:
np.isinf(product_features["revenue_per_unit"]).sum()

np.int64(0)

In [17]:
product_features["revenue_per_unit"].describe()

count    32951.000000
mean       145.302464
std        246.895756
min          0.850000
25%         39.900000
50%         79.000000
75%        154.900000
max       6735.000000
Name: revenue_per_unit, dtype: float64

In [18]:
product_features[
    [
        "total_revenue",
        "total_units_sold",
        "revenue_per_unit"
    ]
].head(10)

   total_revenue  total_units_sold  revenue_per_unit
0         101.65                 1            101.65
1         129.90                 1            129.90
2         229.00                 1            229.00
3         117.80                 2             58.90
4         199.00                 1            199.00
5          52.00                 1             52.00
6         498.00                 2            249.00
7         350.10                 9             38.90
8          78.90                 1             78.90
9         489.86                14             34.99