In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [25]:
from src.preprocessing import convert_dtypes
from src.data_loader import load_data, load_query
from src.preprocessing import missing_value_summary

In [3]:
customer_df = load_data("customer_summary")
order_df = load_data("order_summary")
product_df = load_data("product_summary")
seller_df = load_data("seller_summary")

In [4]:
customer_df.head(5)

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,1,12.00,141.90,5.00,6.00,2018-05-10,2018-05-10,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,1,8.29,27.19,4.00,3.00,2018-05-07,2018-05-07,0
2,0000f46a3911fa3c0805444483337064,1,86.22,1,17.22,86.22,3.00,26.00,2017-03-10,2017-03-10,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,1,17.63,43.62,4.00,20.00,2017-10-12,2017-10-12,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,1,16.89,196.89,5.00,13.00,2017-11-14,2017-11-14,0

### Preprocessing task 1: applying conversion of data types (object) to numeric and datetime datatypes based on data value

In [5]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95420 entries, 0 to 95419
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      95420 non-null  str
 1   total_orders            95420 non-null  int64
 2   total_spent             95419 non-null  object
 3   total_products          95420 non-null  object
 4   total_freight_paid      95420 non-null  object
 5   avg_order_value         95419 non-null  object
 6   avg_review_score        94721 non-null  object
 7   avg_delivery_days       93356 non-null  object
 8   first_purchase          95420 non-null  object
 9   last_purchase           95420 non-null  object
 10  customer_lifetime_days  95420 non-null  int64
dtypes: int64(2), object(8), str(1)
memory usage: 8.0+ MB

### Converting the object data type into numeric and datetime data type

In [6]:
customer_numeric_columns = [
    "total_spent",
    "total_products",
    "total_freight_paid",
    "avg_order_value",
    "avg_review_score",
    "avg_delivery_days"
]

customer_datetime_columns = [
    "first_purchase",
    "last_purchase"
]

In [7]:
customer_df = convert_dtypes(customer_df, numeric_columns = customer_numeric_columns, datetime_columns = customer_datetime_columns)

### Now Verifying

In [8]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95420 entries, 0 to 95419
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      95420 non-null  str
 1   total_orders            95420 non-null  int64
 2   total_spent             95419 non-null  float64
 3   total_products          95420 non-null  float64
 4   total_freight_paid      95420 non-null  float64
 5   avg_order_value         95419 non-null  float64
 6   avg_review_score        94721 non-null  float64
 7   avg_delivery_days       93356 non-null  float64
 8   first_purchase          95420 non-null  datetime64[s]
 9   last_purchase           95420 non-null  datetime64[s]
 10  customer_lifetime_days  95420 non-null  int64
dtypes: datetime64[s](2), float64(6), int64(2), str(1)
memory usage: 8.0 MB

### Now checking the order_df info

In [9]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  object
 13  total_freight                  98666 non-null  object
 14  total_payment                  98665 non-null  object
 15  product_payment                98665 non-null  object
 16  review_score                   97917 non-null  object
dtypes: datetime64[us](5), float64(2), int64(2), object(5), str(3)
memory usage: 12.8+ MB

### Applying conversion

In [10]:
order_numeric_columns = [
    "total_product_price",
    "total_freight",
    "total_payment",
    "product_payment",
    "review_score"
]

order_df = convert_dtypes(
    order_df,
    numeric_columns=order_numeric_columns
)

### Verifying

In [11]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  float64
 13  total_freight                  98666 non-null  float64
 14  total_payment                  98665 non-null  float64
 15  product_payment                98665 non-null  float64
 16  review_score                   97917 non-null  float64
dtypes: datetime64[us](5), float64(7), int64(2), str(3)
memory usage: 12.8 MB

### Checking for product_df info

In [12]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  object
 5   total_freight          32951 non-null  object
 6   avg_price              32951 non-null  object
 7   avg_review_score       32789 non-null  object
 8   avg_delivery_days      32214 non-null  object
dtypes: int64(2), object(5), str(2)
memory usage: 2.3+ MB

### Applying convertion

In [13]:
product_numeric_columns = [
    "total_revenue",
    "total_freight",
    "avg_price",
    "avg_review_score",
    "avg_delivery_days"
]

product_df = convert_dtypes(
    product_df,
    numeric_columns=product_numeric_columns
)

### Verifying

In [14]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  float64
 5   total_freight          32951 non-null  float64
 6   avg_price              32951 non-null  float64
 7   avg_review_score       32789 non-null  float64
 8   avg_delivery_days      32214 non-null  float64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.3 MB

### Checking seller_df info

In [15]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   object
 6   total_freight      3095 non-null   object
 7   avg_product_price  3095 non-null   object
 8   avg_review_score   3090 non-null   object
 9   avg_delivery_days  2970 non-null   object
dtypes: int64(2), object(5), str(3)
memory usage: 241.9+ KB

### Applying conversion

In [16]:
seller_numeric_columns = [
    "total_revenue",
    "total_freight",
    "avg_product_price",
    "avg_review_score",
    "avg_delivery_days"
]

seller_df = convert_dtypes(
    seller_df,
    numeric_columns=seller_numeric_columns
)

### Verifying

In [17]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   float64
 6   total_freight      3095 non-null   float64
 7   avg_product_price  3095 non-null   float64
 8   avg_review_score   3090 non-null   float64
 9   avg_delivery_days  2970 non-null   float64
dtypes: float64(5), int64(2), str(3)
memory usage: 241.9 KB

### Preprocesssing task 2: Missing Value Handling

In [19]:
customer_missing_summary = missing_value_summary(customer_df)

In [20]:
customer_missing_summary

                   missing_values  missing_percentage
avg_delivery_days            2064                2.16
avg_review_score              699                0.73
avg_order_value                 1                0.00
total_spent                     1                0.00

In [21]:
customer_df[
    customer_df["avg_delivery_days"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
44,001ae44fa04911a9e9577356dce6c63c,1,116.23,1.0,16.33,116.23,NaN,NaN,2017-11-06,2017-11-06,0
58,0029bd580d3012618731f5abb174a07f,1,52.38,1.0,12.48,52.38,2.0,NaN,2017-11-02,2017-11-02,0
234,009a0802534f904b40b9d512b49794e1,1,91.29,1.0,14.29,91.29,5.0,NaN,2017-11-16,2017-11-16,0
306,00ca7e6a87ceddccce3ff015000be61b,1,55.06,1.0,17.06,55.06,1.0,NaN,2018-03-19,2018-03-19,0
355,00e872ca2fc94e59982286e69f186e0e,1,420.94,1.0,21.04,420.94,1.0,NaN,2017-08-12,2017-08-12,0
...,...,...,...,...,...,...,...,...,...,...,...
95340,ffc4233210eac4ec1711a8b847196d4e,1,94.77,1.0,8.35,94.77,4.0,NaN,2018-06-19,2018-06-19,0
95347,ffca77d46c6d7d815549a5e4482dba2f,1,155.34,1.0,13.70,155.34,NaN,NaN,2018-03-22,2018-03-22,0
95365,ffdde6e4dcb6ec3a882cfc6cddef7996,1,796.94,1.0,109.94,796.94,1.0,NaN,2017-12-10,2017-12-10,0
95380,ffe6305176b9431a3eda3cf8904d7eb7,1,57.37,1.0,7.39,57.37,NaN,NaN,2018-06-09,2018-06-09,0
95414,fffcc512b7dfecaffd80f13614af1d16,1,710.70,1.0,22.70,710.70,1.0,NaN,2018-04-11,2018-04-11,0

In [22]:
customer_df[
    customer_df["avg_review_score"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
44,001ae44fa04911a9e9577356dce6c63c,1,116.23,1.0,16.33,116.23,NaN,NaN,2017-11-06,2017-11-06,0
287,00bee19e1199bc5cede1c674177b9e22,1,673.69,1.0,23.79,673.69,NaN,26.0,2017-11-17,2017-11-17,0
376,00fb9cc86736fe3782dbc828a2eea4a6,1,92.57,1.0,13.57,92.57,NaN,14.0,2017-12-20,2017-12-20,0
875,025cf7c2f32536f0be1ab412bb6602d2,1,1898.61,1.0,110.61,1898.61,NaN,12.0,2018-08-17,2018-08-17,0
970,02a2a0a9627a062602de754d75038ce4,1,532.49,1.0,30.49,532.49,NaN,NaN,2018-08-08,2018-08-08,0
...,...,...,...,...,...,...,...,...,...,...,...
95254,ff905cb313cb121a840dafe5a7a9170f,1,194.50,1.0,15.01,194.50,NaN,8.0,2017-12-06,2017-12-06,0
95311,ffb3cbd5e1e507679e2db84c515410a5,1,110.63,1.0,15.73,110.63,NaN,15.0,2018-08-15,2018-08-15,0
95347,ffca77d46c6d7d815549a5e4482dba2f,1,155.34,1.0,13.70,155.34,NaN,NaN,2018-03-22,2018-03-22,0
95372,ffe0c10afc687bcf34a0451f2b87dd9b,1,215.76,1.0,36.76,215.76,NaN,10.0,2018-02-08,2018-02-08,0
95380,ffe6305176b9431a3eda3cf8904d7eb7,1,57.37,1.0,7.39,57.37,NaN,NaN,2018-06-09,2018-06-09,0

In [23]:
customer_df[
    customer_df["avg_order_value"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
48972,830d5b7aaa3b6f1e9ad63703bec97d23,1,NaN,3.0,8.49,NaN,1.0,55.0,2016-09-15,2016-09-15,0

In [24]:
customer_df[
    customer_df["total_spent"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
48972,830d5b7aaa3b6f1e9ad63703bec97d23,1,NaN,3.0,8.49,NaN,1.0,55.0,2016-09-15,2016-09-15,0

In [28]:
query = """
SELECT
    order_status,
    COUNT(*) AS count,
    SUM(COUNT(*)) OVER() AS Total
FROM order_summary
WHERE delivery_days IS NULL
GROUP BY order_status;
"""

check = load_query(query)

In [29]:
check

  order_status  count total
0     approved      2  2190
1     canceled    455  2190
2    delivered      8  2190
3     invoiced    312  2190
4   processing    301  2190
5      shipped   1106  2190
6  unavailable      6  2190

In [30]:
query = """
SELECT
    order_id,
    order_status,
    order_purchase_timestamp,
    order_delivered_customer_date,
    delivery_days
FROM order_summary
WHERE delivery_days IS NULL
AND order_status = 'delivered';

"""

In [31]:
check = load_query(query)
check

,order_id,order_status,order_purchase_timestamp,order_delivered_customer_date,delivery_days
0,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,None,None
1,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,None,None
2,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,None,None
3,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,None,None
4,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,None,None
5,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,None,None
6,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,None,None
7,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,None,None