In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [2]:
from src.preprocessing import convert_dtypes
from src.data_loader import load_data, load_query
from src.preprocessing import missing_value_summary
from src.preprocessing import outlier_summary

In [3]:
customer_df = load_data("customer_summary")
order_df = load_data("order_summary")
product_df = load_data("product_summary")
seller_df = load_data("seller_summary")

In [4]:
customer_df.head(5)

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,1,12.00,141.90,5.00,6.00,2018-05-10,2018-05-10,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,1,8.29,27.19,4.00,3.00,2018-05-07,2018-05-07,0
2,0000f46a3911fa3c0805444483337064,1,86.22,1,17.22,86.22,3.00,26.00,2017-03-10,2017-03-10,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,1,17.63,43.62,4.00,20.00,2017-10-12,2017-10-12,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,1,16.89,196.89,5.00,13.00,2017-11-14,2017-11-14,0

### Preprocessing task 1: applying conversion of data types (object) to numeric and datetime datatypes based on data value

In [5]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95420 entries, 0 to 95419
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      95420 non-null  str
 1   total_orders            95420 non-null  int64
 2   total_spent             95419 non-null  object
 3   total_products          95420 non-null  object
 4   total_freight_paid      95420 non-null  object
 5   avg_order_value         95419 non-null  object
 6   avg_review_score        94721 non-null  object
 7   avg_delivery_days       93356 non-null  object
 8   first_purchase          95420 non-null  object
 9   last_purchase           95420 non-null  object
 10  customer_lifetime_days  95420 non-null  int64
dtypes: int64(2), object(8), str(1)
memory usage: 8.0+ MB

### Converting the object data type into numeric and datetime data type

In [6]:
customer_numeric_columns = [
    "total_spent",
    "total_products",
    "total_freight_paid",
    "avg_order_value",
    "avg_review_score",
    "avg_delivery_days"
]

customer_datetime_columns = [
    "first_purchase",
    "last_purchase"
]

In [7]:
customer_df = convert_dtypes(customer_df, numeric_columns = customer_numeric_columns, datetime_columns = customer_datetime_columns)

### Now Verifying

In [8]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95420 entries, 0 to 95419
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      95420 non-null  str
 1   total_orders            95420 non-null  int64
 2   total_spent             95419 non-null  float64
 3   total_products          95420 non-null  float64
 4   total_freight_paid      95420 non-null  float64
 5   avg_order_value         95419 non-null  float64
 6   avg_review_score        94721 non-null  float64
 7   avg_delivery_days       93356 non-null  float64
 8   first_purchase          95420 non-null  datetime64[s]
 9   last_purchase           95420 non-null  datetime64[s]
 10  customer_lifetime_days  95420 non-null  int64
dtypes: datetime64[s](2), float64(6), int64(2), str(1)
memory usage: 8.0 MB

### Now checking the order_df info

In [9]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  object
 13  total_freight                  98666 non-null  object
 14  total_payment                  98665 non-null  object
 15  product_payment                98665 non-null  object
 16  review_score                   97917 non-null  object
dtypes: datetime64[us](5), float64(2), int64(2), object(5), str(3)
memory usage: 12.8+ MB

### Applying conversion

In [10]:
order_numeric_columns = [
    "total_product_price",
    "total_freight",
    "total_payment",
    "product_payment",
    "review_score"
]

order_df = convert_dtypes(
    order_df,
    numeric_columns=order_numeric_columns
)

### Verifying

In [11]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  float64
 13  total_freight                  98666 non-null  float64
 14  total_payment                  98665 non-null  float64
 15  product_payment                98665 non-null  float64
 16  review_score                   97917 non-null  float64
dtypes: datetime64[us](5), float64(7), int64(2), str(3)
memory usage: 12.8 MB

### Checking for product_df info

In [12]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  object
 5   total_freight          32951 non-null  object
 6   avg_price              32951 non-null  object
 7   avg_review_score       32789 non-null  object
 8   avg_delivery_days      32214 non-null  object
dtypes: int64(2), object(5), str(2)
memory usage: 2.3+ MB

### Applying convertion

In [13]:
product_numeric_columns = [
    "total_revenue",
    "total_freight",
    "avg_price",
    "avg_review_score",
    "avg_delivery_days"
]

product_df = convert_dtypes(
    product_df,
    numeric_columns=product_numeric_columns
)

### Verifying

In [14]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  float64
 5   total_freight          32951 non-null  float64
 6   avg_price              32951 non-null  float64
 7   avg_review_score       32789 non-null  float64
 8   avg_delivery_days      32214 non-null  float64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.3 MB

### Checking seller_df info

In [15]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   object
 6   total_freight      3095 non-null   object
 7   avg_product_price  3095 non-null   object
 8   avg_review_score   3090 non-null   object
 9   avg_delivery_days  2970 non-null   object
dtypes: int64(2), object(5), str(3)
memory usage: 241.9+ KB

### Applying conversion

In [16]:
seller_numeric_columns = [
    "total_revenue",
    "total_freight",
    "avg_product_price",
    "avg_review_score",
    "avg_delivery_days"
]

seller_df = convert_dtypes(
    seller_df,
    numeric_columns=seller_numeric_columns
)

### Verifying

In [17]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   float64
 6   total_freight      3095 non-null   float64
 7   avg_product_price  3095 non-null   float64
 8   avg_review_score   3090 non-null   float64
 9   avg_delivery_days  2970 non-null   float64
dtypes: float64(5), int64(2), str(3)
memory usage: 241.9 KB

### Preprocesssing task 2: Missing Value Handling

In [18]:
customer_missing_summary = missing_value_summary(customer_df)

In [19]:
customer_missing_summary

                   missing_values  missing_percentage
avg_delivery_days            2064                2.16
avg_review_score              699                0.73
avg_order_value                 1                0.00
total_spent                     1                0.00

In [20]:
customer_df[
    customer_df["avg_delivery_days"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
44,001ae44fa04911a9e9577356dce6c63c,1,116.23,1.0,16.33,116.23,NaN,NaN,2017-11-06,2017-11-06,0
58,0029bd580d3012618731f5abb174a07f,1,52.38,1.0,12.48,52.38,2.0,NaN,2017-11-02,2017-11-02,0
234,009a0802534f904b40b9d512b49794e1,1,91.29,1.0,14.29,91.29,5.0,NaN,2017-11-16,2017-11-16,0
306,00ca7e6a87ceddccce3ff015000be61b,1,55.06,1.0,17.06,55.06,1.0,NaN,2018-03-19,2018-03-19,0
355,00e872ca2fc94e59982286e69f186e0e,1,420.94,1.0,21.04,420.94,1.0,NaN,2017-08-12,2017-08-12,0
...,...,...,...,...,...,...,...,...,...,...,...
95340,ffc4233210eac4ec1711a8b847196d4e,1,94.77,1.0,8.35,94.77,4.0,NaN,2018-06-19,2018-06-19,0
95347,ffca77d46c6d7d815549a5e4482dba2f,1,155.34,1.0,13.70,155.34,NaN,NaN,2018-03-22,2018-03-22,0
95365,ffdde6e4dcb6ec3a882cfc6cddef7996,1,796.94,1.0,109.94,796.94,1.0,NaN,2017-12-10,2017-12-10,0
95380,ffe6305176b9431a3eda3cf8904d7eb7,1,57.37,1.0,7.39,57.37,NaN,NaN,2018-06-09,2018-06-09,0
95414,fffcc512b7dfecaffd80f13614af1d16,1,710.70,1.0,22.70,710.70,1.0,NaN,2018-04-11,2018-04-11,0

In [21]:
customer_df[
    customer_df["avg_review_score"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
44,001ae44fa04911a9e9577356dce6c63c,1,116.23,1.0,16.33,116.23,NaN,NaN,2017-11-06,2017-11-06,0
287,00bee19e1199bc5cede1c674177b9e22,1,673.69,1.0,23.79,673.69,NaN,26.0,2017-11-17,2017-11-17,0
376,00fb9cc86736fe3782dbc828a2eea4a6,1,92.57,1.0,13.57,92.57,NaN,14.0,2017-12-20,2017-12-20,0
875,025cf7c2f32536f0be1ab412bb6602d2,1,1898.61,1.0,110.61,1898.61,NaN,12.0,2018-08-17,2018-08-17,0
970,02a2a0a9627a062602de754d75038ce4,1,532.49,1.0,30.49,532.49,NaN,NaN,2018-08-08,2018-08-08,0
...,...,...,...,...,...,...,...,...,...,...,...
95254,ff905cb313cb121a840dafe5a7a9170f,1,194.50,1.0,15.01,194.50,NaN,8.0,2017-12-06,2017-12-06,0
95311,ffb3cbd5e1e507679e2db84c515410a5,1,110.63,1.0,15.73,110.63,NaN,15.0,2018-08-15,2018-08-15,0
95347,ffca77d46c6d7d815549a5e4482dba2f,1,155.34,1.0,13.70,155.34,NaN,NaN,2018-03-22,2018-03-22,0
95372,ffe0c10afc687bcf34a0451f2b87dd9b,1,215.76,1.0,36.76,215.76,NaN,10.0,2018-02-08,2018-02-08,0
95380,ffe6305176b9431a3eda3cf8904d7eb7,1,57.37,1.0,7.39,57.37,NaN,NaN,2018-06-09,2018-06-09,0

In [22]:
customer_df[
    customer_df["avg_order_value"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
48972,830d5b7aaa3b6f1e9ad63703bec97d23,1,NaN,3.0,8.49,NaN,1.0,55.0,2016-09-15,2016-09-15,0

In [23]:
customer_df[
    customer_df["total_spent"].isna()
]

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
48972,830d5b7aaa3b6f1e9ad63703bec97d23,1,NaN,3.0,8.49,NaN,1.0,55.0,2016-09-15,2016-09-15,0

In [24]:
customer_df = customer_df.dropna(
    subset=["total_spent", "avg_order_value"]
)

In [25]:
query = """
SELECT
    order_status,
    COUNT(*) AS count,
    SUM(COUNT(*)) OVER() AS Total
FROM order_summary
WHERE delivery_days IS NULL
GROUP BY order_status;
"""

check = load_query(query)

In [26]:
check

  order_status  count total
0     approved      2  2190
1     canceled    455  2190
2    delivered      8  2190
3     invoiced    312  2190
4   processing    301  2190
5      shipped   1106  2190
6  unavailable      6  2190

In [27]:
query = """
SELECT
    order_id,
    order_status,
    order_purchase_timestamp,
    order_delivered_customer_date,
    delivery_days
FROM order_summary
WHERE delivery_days IS NULL
AND order_status = 'delivered';

"""

In [28]:
check = load_query(query)
check

,order_id,order_status,order_purchase_timestamp,order_delivered_customer_date,delivery_days
0,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,None,None
1,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,None,None
2,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,None,None
3,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,None,None
4,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,None,None
5,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,None,None
6,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,None,None
7,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,None,None

### Preprocessing task 3: Duplicate analysis

In [29]:
print("Entire duplicate rows:", customer_df.duplicated().sum())

Entire duplicate rows: 0

In [30]:
print(
    "Duplicate customer IDs:",
    customer_df["customer_unique_id"].duplicated().sum()
)

Duplicate customer IDs: 0

### Preprocessing task 4: Outlier Detection

#### Step 1: select numerical columns

In [31]:
numerical_columns = customer_df.select_dtypes(include=["int64", "float64"]).columns

In [32]:
numerical_columns

Index(['total_orders', 'total_spent', 'total_products', 'total_freight_paid',
       'avg_order_value', 'avg_review_score', 'avg_delivery_days',
       'customer_lifetime_days'],
      dtype='str')

#### step 2: Run the outlier analysis summary function

In [33]:
customer_outlier_summary = outlier_summary(customer_df, numerical_columns)

In [34]:
customer_outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
0,total_orders,1.00,1.00,0.00,1.00,1.00,2913,3.05
1,total_spent,63.10,183.27,120.17,-117.16,363.52,7595,7.96
2,total_products,1.00,1.00,0.00,1.00,1.00,11868,12.44
3,total_freight_paid,14.08,25.54,11.46,-3.11,42.73,9216,9.66
4,avg_order_value,62.44,177.15,114.71,-109.62,349.22,7534,7.90
5,avg_review_score,4.00,5.00,1.00,2.50,6.50,13313,13.95
6,avg_delivery_days,7.00,16.00,9.00,-6.50,29.50,4563,4.78
7,customer_lifetime_days,0.00,0.00,0.00,0.00,0.00,2085,2.19

In [35]:
customer_outlier_summary.sort_values(
    by="Outlier Percentage",
    ascending=False
)

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
5,avg_review_score,4.00,5.00,1.00,2.50,6.50,13313,13.95
2,total_products,1.00,1.00,0.00,1.00,1.00,11868,12.44
3,total_freight_paid,14.08,25.54,11.46,-3.11,42.73,9216,9.66
1,total_spent,63.10,183.27,120.17,-117.16,363.52,7595,7.96
4,avg_order_value,62.44,177.15,114.71,-109.62,349.22,7534,7.90
6,avg_delivery_days,7.00,16.00,9.00,-6.50,29.50,4563,4.78
0,total_orders,1.00,1.00,0.00,1.00,1.00,2913,3.05
7,customer_lifetime_days,0.00,0.00,0.00,0.00,0.00,2085,2.19

## For Order

### Step 1: Inspect the dataset

In [36]:
order_df.shape

(98666, 17)

In [37]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  float64
 13  total_freight                  98666 non-null  float64
 14  total_payment                  98665 non-null  float64
 15  product_payment                98665 non-null  float64
 16  review_score                   97917 non-null  float64
dtypes: datetime64[us](5), float64(7), int64(2), str(3)
memory usage: 12.8 MB

In [38]:
order_df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers,total_product_price,total_freight,total_payment,product_payment,review_score
count,98666,98652,97657,96476,98666,96476.000000,96476.000000,98666.000000,98666.000000,98666.000000,98666.000000,98665.000000,98665.000000,97917.000000
mean,2017-12-31 22:05:22.366559,2018-01-01 09:30:11.667913,2018-01-04 21:56:02.570537,2018-01-14 12:09:19.035542,2018-01-24 16:36:25.409360,12.497336,-11.876881,1.141731,1.013622,137.754076,22.823562,160.606904,137.783197,4.105055
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,0.000000,-147.000000,1.000000,1.000000,0.850000,0.000000,9.590000,0.850000,1.000000
25%,2017-09-12 23:21:27.500000,2017-09-13 15:37:19.500000,2017-09-15 22:31:51,2017-09-25 22:07:22.250000,2017-10-04 00:00:00,7.000000,-17.000000,1.000000,1.000000,45.900000,13.850000,62.000000,45.900000,4.000000
50%,2018-01-19 18:02:47,2018-01-20 09:10:39,2018-01-24 16:12:38,2018-02-02 19:28:10.500000,2018-02-15 00:00:00,10.000000,-12.000000,1.000000,1.000000,86.900000,17.170000,105.290000,86.900000,5.000000
75%,2018-05-04 20:05:35.250000,2018-05-05 07:16:04,2018-05-08 13:38:00,2018-05-15 22:48:52.250000,2018-05-28 00:00:00,16.000000,-7.000000,1.000000,1.000000,149.900000,24.040000,176.880000,149.900000,5.000000
max,2018-09-03 09:06:57,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,210.000000,188.000000,21.000000,5.000000,13440.000000,1794.960000,13664.080000,13440.000000,5.000000
std,NaN,NaN,NaN,NaN,NaN,9.555460,10.183854,0.538452,0.122297,210.645145,21.650909,220.484252,210.661454,1.330316

### Step 2: Missing value analysis

In [39]:
order_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date     1009
order_delivered_customer_date    2190
order_estimated_delivery_date       0
delivery_days                    2190
delivery_delay_days              2190
total_items                         0
distinct_sellers                    0
total_product_price                 0
total_freight                       0
total_payment                       1
product_payment                     1
review_score                      749
dtype: int64

In [41]:
order_missing_summary = missing_value_summary(order_df)

In [43]:
order_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers,total_product_price,total_freight,total_payment,product_payment,review_score
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,7.0,-9.0,1,1,58.90,13.29,72.19,58.90,5.0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,16.0,-3.0,1,1,239.90,19.93,259.83,239.90,4.0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,8.0,-14.0,1,1,199.00,17.87,216.87,199.00,5.0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,6.0,-6.0,1,1,12.99,12.79,25.78,12.99,4.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,25.0,-16.0,1,1,199.90,18.14,218.04,199.90,5.0

In [42]:
order_missing_summary

                               missing_values  missing_percentage
delivery_days                            2190                2.22
order_delivered_customer_date            2190                2.22
delivery_delay_days                      2190                2.22
order_delivered_carrier_date             1009                1.02
review_score                              749                0.76
order_approved_at                          14                0.01
total_payment                               1                0.00
product_payment                             1                0.00

In [44]:
order_df[
    order_df["order_approved_at"].isna()
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers,total_product_price,total_freight,total_payment,product_payment,review_score
7222,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20,13.0,-18.0,1,1,79.99,15.77,95.76,79.99,5.0
16680,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31,13.0,-28.0,1,1,79.99,26.82,106.81,79.99,4.0
17963,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20,14.0,-17.0,1,1,135.00,19.23,154.23,135.00,5.0
23110,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23,14.0,-20.0,1,1,133.99,23.20,157.19,133.99,3.0
31595,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29,17.0,-22.0,1,1,59.90,17.16,77.06,59.90,5.0
35717,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31,19.0,-22.0,1,1,79.99,26.82,106.81,79.99,5.0
43169,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16,18.0,-38.0,1,1,45.90,14.52,60.42,45.90,2.0
43192,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17,11.0,-16.0,1,1,49.99,15.53,65.52,49.99,5.0
52234,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21,12.0,-19.0,2,1,98.00,29.04,127.04,98.00,4.0
53225,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21,12.0,-19.0,1,1,379.00,17.86,396.86,379.00,5.0
74665,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01,11.0,-30.0,1,1,39.99,14.52,54.51,39.99,4.0
82820,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27,11.0,-25.0,1,1,149.80,13.63,163.43,149.80,5.0
83145,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22,12.0,-20.0,1,1,28.99,10.96,39.95,28.99,5.0
86565,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17,11.0,-16.0,1,1,309.90,39.11,349.01,309.90,4.0

In [45]:
order_df[order_df["total_payment"].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers,total_product_price,total_freight,total_payment,product_payment,review_score
73845,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04,55.0,36.0,3,1,134.97,8.49,NaN,NaN,1.0

In [46]:
order_df["total_payment"] = order_df["total_payment"].fillna(order_df["total_product_price"] + order_df["total_freight"])
order_df["product_payment"] = order_df["product_payment"].fillna(order_df["total_product_price"])

In [47]:
order_df[order_df["total_payment"].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, delivery_days, delivery_delay_days, total_items, distinct_sellers, total_product_price, total_freight, total_payment, product_payment, review_score]
Index: []

### Step 3: Duplicate analysis

In [48]:
print("Entire duplicate rows:", order_df.duplicated().sum())

Entire duplicate rows: 0

In [49]:
order_df["order_id"].duplicated().sum()

np.int64(0)

### Step 4: Outlier Analysis

#### select the numerical columns

In [50]:
numerical_columns = order_df.select_dtypes(include=["int64", "float64"]).columns

In [51]:
numerical_columns

Index(['delivery_days', 'delivery_delay_days', 'total_items',
       'distinct_sellers', 'total_product_price', 'total_freight',
       'total_payment', 'product_payment', 'review_score'],
      dtype='str')

In [54]:
order_outlier_summary = outlier_summary(order_df, numerical_columns).sort_values(by = "Outlier Percentage", ascending=False)

In [55]:
order_outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
8,review_score,4.00,5.00,1.00,2.50,6.50,13849,14.04
5,total_freight,13.85,24.04,10.19,-1.44,39.33,9941,10.08
2,total_items,1.00,1.00,0.00,1.00,1.00,9803,9.94
7,product_payment,45.90,149.90,104.00,-110.10,305.90,7917,8.02
4,total_product_price,45.90,149.90,104.00,-110.10,305.90,7913,8.02
6,total_payment,62.00,176.88,114.88,-110.32,349.20,7777,7.88
0,delivery_days,7.00,16.00,9.00,-6.50,29.50,4732,4.80
1,delivery_delay_days,-17.00,-7.00,10.00,-32.00,8.00,4301,4.36
3,distinct_sellers,1.00,1.00,0.00,1.00,1.00,1278,1.30

## Product analysis

### step 1: inspect the product data

In [56]:
product_df.head(5)

,product_id,product_category_name,total_units_sold,total_orders,total_revenue,total_freight,avg_price,avg_review_score,avg_delivery_days
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,1,1,101.65,18.59,101.65,5.0,17.0
1,00088930e925c41fd95ebfe695fd2655,automotivo,1,1,129.90,13.93,129.90,4.0,11.0
2,0009406fd7479715e4bef61dd91f2462,cama_mesa_banho,1,1,229.00,13.10,229.00,1.0,16.0
3,000b8f95fcb9e0096488278317764d19,utilidades_domesticas,2,2,117.80,39.20,58.90,5.0,6.5
4,000d9be29b5207b54e86aa1b1ac54872,relogios_presentes,1,1,199.00,19.27,199.00,5.0,7.0

In [57]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  float64
 5   total_freight          32951 non-null  float64
 6   avg_price              32951 non-null  float64
 7   avg_review_score       32789 non-null  float64
 8   avg_delivery_days      32214 non-null  float64
dtypes: float64(5), int64(2), str(2)
memory usage: 2.3 MB

In [58]:
product_df.shape

(32951, 9)

### Step 2: Missing Value Analysis

In [59]:
product_df.isnull().sum()

product_id                 0
product_category_name    610
total_units_sold           0
total_orders               0
total_revenue              0
total_freight              0
avg_price                  0
avg_review_score         162
avg_delivery_days        737
dtype: int64

In [60]:
product_missing_summary = missing_value_summary(product_df)

In [61]:
product_missing_summary

                       missing_values  missing_percentage
avg_delivery_days                 737                2.24
product_category_name             610                1.85
avg_review_score                  162                0.49

### Step 3: Duplicate analysis

In [62]:
product_df.duplicated().sum()

np.int64(0)

In [63]:
product_df["product_id"].duplicated().sum()

np.int64(0)

### Step 4: Outlier Detection

In [64]:
numerical_columns = product_df.select_dtypes(include=["int64", "float64"]).columns
numerical_columns

Index(['total_units_sold', 'total_orders', 'total_revenue', 'total_freight',
       'avg_price', 'avg_review_score', 'avg_delivery_days'],
      dtype='str')

In [65]:
product_outier_summary = outlier_summary(product_df, numerical_columns).sort_values(by = "Outlier Percentage", ascending=False)

In [66]:
product_outier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
1,total_orders,1.00,2.00,1.0,-0.50,3.50,5538,16.81
2,total_revenue,59.90,329.00,269.1,-343.75,732.65,3717,11.28
3,total_freight,15.94,58.04,42.1,-47.21,121.19,3585,10.88
0,total_units_sold,1.00,3.00,2.0,-2.00,6.00,3102,9.41
4,avg_price,39.90,154.90,115.0,-132.60,327.40,2817,8.55
5,avg_review_score,3.60,5.00,1.4,1.50,7.10,2773,8.42
6,avg_delivery_days,7.00,15.00,8.0,-5.00,27.00,1384,4.20

## Seller df analysis

### Step 1 : Inspect the data

In [67]:
seller_df.head(5)

,seller_id,seller_city,seller_state,total_orders,total_units_sold,total_revenue,total_freight,avg_product_price,avg_review_score,avg_delivery_days
0,0015a82c2db000af6aaaf3ae2ecb0532,santo andre,SP,3,3,2685.00,63.06,895.00,3.67,10.67
1,001cca7ae9ae17fb1caed9dfb1094831,cariacica,ES,200,239,25080.03,8854.14,104.94,3.90,13.11
2,001e6ad469a905060d959994f1b41e4f,sao goncalo,RJ,1,1,250.00,17.94,250.00,1.00,NaN
3,002100f778ceb8431b7a1020ff7ab48f,franca,SP,51,55,1234.50,793.66,22.45,3.98,16.00
4,003554e2dce176b5555353e4f3555ac8,goiania,GO,1,1,120.00,19.38,120.00,5.00,4.00

In [68]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   float64
 6   total_freight      3095 non-null   float64
 7   avg_product_price  3095 non-null   float64
 8   avg_review_score   3090 non-null   float64
 9   avg_delivery_days  2970 non-null   float64
dtypes: float64(5), int64(2), str(3)
memory usage: 241.9 KB

In [69]:
seller_df.shape

(3095, 10)

### Step 2: Missing value analysis

In [70]:
seller_df.isnull().sum()

seller_id              0
seller_city            0
seller_state           0
total_orders           0
total_units_sold       0
total_revenue          0
total_freight          0
avg_product_price      0
avg_review_score       5
avg_delivery_days    125
dtype: int64

In [71]:
seller_missing_summary = missing_value_summary(seller_df)
seller_missing_summary

                   missing_values  missing_percentage
avg_delivery_days             125                4.04
avg_review_score                5                0.16

### Step 3: Duplicate analysis

In [72]:
seller_df.duplicated().sum()

np.int64(0)

In [73]:
seller_df["seller_id"].duplicated().sum()

np.int64(0)

### Step 4: Outlier Detection

In [76]:
numerical_columns = seller_df.select_dtypes(include=["int64", "float64"]).columns

In [77]:
numerical_columns

Index(['total_orders', 'total_units_sold', 'total_revenue', 'total_freight',
       'avg_product_price', 'avg_review_score', 'avg_delivery_days'],
      dtype='str')

In [78]:
seller_outlier_summary = outlier_summary(seller_df, numerical_columns).sort_values(by = "Outlier Percentage", ascending=False)

In [79]:
seller_outlier_summary

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier Percentage
0,total_orders,2.00,21.50,19.50,-27.25,50.75,421,13.60
1,total_units_sold,2.00,24.00,22.00,-31.00,57.00,416,13.44
2,total_revenue,208.85,3280.83,3071.98,-4399.12,7888.80,380,12.28
3,total_freight,46.17,558.17,512.00,-721.83,1326.17,371,11.99
4,avg_product_price,52.18,174.00,121.81,-130.53,356.71,298,9.63
5,avg_review_score,3.71,4.60,0.89,2.38,5.93,246,7.95
6,avg_delivery_days,8.21,14.09,5.88,-0.60,22.90,142,4.59